import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="fixed top-0 left-0 w-full flex justify-between p-4 bg-gray-800 text-white shadow-md z-50">
          <a href="/" className="text-white hover:text-gray-200">
            Home
          </a>
        </nav>

        <main className="pt-16 bg-blue-50">{children}</main>
      </body>
    </html>
  );
}

